---
controller_execution_environments:
  - name: windows workshop execution environment
    image: quay.io/acme_corp/windows_ee:latest
    pull: missing
    organization: "{{ my_organization }}"
    credential: quay.io

  - name: amazon_aws_ee
    image: quay.io/zigfreed/amazon_aws_ee:latest
    pull: missing
    organization: "{{ my_organization }}"
    credential: quay.io
